// ─── MCL Cylinder Delivery — REAL seed data ──────────────────────────────────
// Derived from: "Peshawar Sale & Purchase Report June 25 to July 26.xlsx"
// (Multan Chemicals Limited, Peshawar branch, 01-Jul-2025 → 29-Jun-2026).
// Product names, sizes, item codes, customer names and customer codes are REAL,
// taken from the report. Phone numbers, addresses, deposits, payment terms,
// confirm methods, routes and credit limits are PLAUSIBLE FILL — the source
// report carries none of them. See docs/data-profile.md for provenance.

import type { Product, Client } from './types';

/**
 * Products distilled from the real item list.
 * `unitPrice` is PKR per FILLED CYLINDER, computed as (median rate in the
 * report for that gas) x (cylinder size), rounded to a sane retail figure.
 * The source prices per M3 / litre / kg; the app sells whole cylinders.
 */
export const realProducts: Omit<Product, 'collectionPrice'>[] = [
  {
    id: 1,
    sku: 'OXY-68-IND',
    name: 'Oxygen 99.6% Industrial',
    size: '6.80 M3',
    oracleItemCode: 'ITM-OXY-68-IND',
    bookTypeId: 1,
    unitPrice: 9520,
    depositPerCylinder: 15000,
  },
  {
    id: 2,
    sku: 'OXY-68-MED',
    name: 'Oxygen 99.6% Medical',
    size: '6.80 M3',
    oracleItemCode: 'ITM-OXY-68-MED',
    bookTypeId: 2,
    unitPrice: 9800,
    depositPerCylinder: 15000,
  },
  {
    id: 3,
    sku: 'OXY-17-MED',
    name: 'Oxygen 99.6% Medical',
    size: '1.70 M3',
    oracleItemCode: 'ITM-OXY-17-MED',
    bookTypeId: 2,
    unitPrice: 2380,
    depositPerCylinder: 8000,
  },
  {
    id: 4,
    sku: 'OXY-34-MED',
    name: 'Oxygen 99.6% Medical',
    size: '3.40 M3',
    oracleItemCode: 'ITM-OXY-34-MED',
    bookTypeId: 2,
    unitPrice: 4760,
    depositPerCylinder: 11000,
  },
  {
    id: 5,
    sku: 'OXY-99-IND',
    name: 'Oxygen 99.6% Industrial',
    size: '9.90 M3',
    oracleItemCode: 'ITM-OXY-99-IND',
    bookTypeId: 1,
    unitPrice: 13860,
    depositPerCylinder: 18000,
  },
  {
    id: 6,
    sku: 'NIT-68',
    name: 'Nitrogen 99.9%',
    size: '6.80 M3',
    oracleItemCode: 'ITM-NIT-68',
    bookTypeId: 1,
    unitPrice: 620,
    depositPerCylinder: 15000,
  },
  {
    id: 7,
    sku: 'LN2-JAR-47',
    name: 'Liquid Nitrogen LN2 Jar',
    size: '47 LTR',
    oracleItemCode: 'ITM-LN2-JAR-47',
    bookTypeId: 5,
    unitPrice: 4935,
    depositPerCylinder: 45000,
  },
  {
    id: 8,
    sku: 'LOX-XL60',
    name: 'Liquid Oxygen Cryogenic XL-60',
    size: '60 LTR',
    oracleItemCode: 'ITM-LOX-XL60',
    bookTypeId: 5,
    unitPrice: 26400,
    depositPerCylinder: 120000,
  },
  {
    id: 9,
    sku: 'ARG-68',
    name: 'Argon 99.99%',
    size: '6.80 M3',
    oracleItemCode: 'ITM-ARG-68',
    bookTypeId: 3,
    unitPrice: 37400,
    depositPerCylinder: 18000,
  },
  {
    id: 10,
    sku: 'CO2-20KG',
    name: 'Carbon Dioxide CO2',
    size: '6.80 (20 KG)',
    oracleItemCode: 'ITM-CO2-20KG',
    bookTypeId: 3,
    unitPrice: 4000,
    depositPerCylinder: 16000,
  },
  {
    id: 11,
    sku: 'DA-98',
    name: 'Dissolved Acetylene 98%',
    size: 'D/A Cylinder',
    oracleItemCode: 'ITM-DA-98',
    bookTypeId: 3,
    unitPrice: 16100,
    depositPerCylinder: 22000,
  },
  {
    id: 12,
    sku: 'LPG-454',
    name: 'LPG Commercial',
    size: '45.4 KG',
    oracleItemCode: 'ITM-LPG-454',
    bookTypeId: 1,
    unitPrice: 11030,
    depositPerCylinder: 12000,
  },
  {
    id: 13,
    sku: 'LPG-118',
    name: 'LPG Domestic',
    size: '11.80 KG',
    oracleItemCode: 'ITM-LPG-118',
    bookTypeId: 1,
    unitPrice: 2870,
    depositPerCylinder: 6000,
  },
  {
    id: 14,
    sku: 'N2O-085',
    name: 'Nitrous Oxide (Medical)',
    size: '0.85 M3',
    oracleItemCode: 'ITM-N2O-085',
    bookTypeId: 2,
    unitPrice: 5500,
    depositPerCylinder: 9000,
  },
];

/**
 * Customers distilled from the real party list (145 distinct parties in the
 * report). These are the 16 highest-value accounts. `oracleCustomerCode` wraps
 * the REAL Oracle customer code found in the sheet's "Customer Code" column.
 * `outstanding` is scaled from real 12-month sales value; credit limits,
 * phones, addresses and areas are plausible fill.
 */
export const realClients: Client[] = [
  {
    id: 1,
    name: 'CMH Peshawar (PWR)',
    address: 'Combined Military Hospital, Peshawar Cantt',
    area: 'Peshawar Cantt',
    contactNumber: '+92-91-9211501',
    oracleCustomerCode: 'CUST-119854',
    paymentTerms: 'credit',
    confirmMethod: 'signature',
    defaultRouteId: 1,
    creditLimit: 8000000,
    outstanding: 3921000,
  },
  {
    id: 2,
    name: 'Jameel Gases Peshawar',
    address: 'Gas Market, Kohat Road, Peshawar',
    area: 'Kohat Road',
    contactNumber: '+92-300-5901122',
    oracleCustomerCode: 'CUST-128079',
    paymentTerms: 'credit',
    confirmMethod: 'signature',
    defaultRouteId: 2,
    creditLimit: 7000000,
    outstanding: 3520000,
  },
  {
    id: 3,
    name: 'Qazi Hussain Ahmad Medical Complex',
    address: 'Nishtarabad, Peshawar',
    area: 'Nishtarabad',
    contactNumber: '+92-91-2265440',
    oracleCustomerCode: 'CUST-121572',
    paymentTerms: 'credit',
    confirmMethod: 'otp',
    defaultRouteId: 1,
    creditLimit: 6500000,
    outstanding: 3214000,
  },
  {
    id: 4,
    name: 'Fine Gases Peshawar',
    address: 'Industrial Estate, Hayatabad, Peshawar',
    area: 'Hayatabad',
    contactNumber: '+92-333-9182204',
    oracleCustomerCode: 'CUST-142337',
    paymentTerms: 'credit',
    confirmMethod: 'signature',
    defaultRouteId: 3,
    creditLimit: 3000000,
    outstanding: 1212000,
  },
  {
    id: 5,
    name: 'Maqsood Medical Complex (MMC)',
    address: 'Dalazak Road, Peshawar',
    area: 'Dalazak Road',
    contactNumber: '+92-91-2551880',
    oracleCustomerCode: 'CUST-131312',
    paymentTerms: 'credit',
    confirmMethod: 'otp',
    defaultRouteId: 1,
    creditLimit: 3000000,
    outstanding: 1188000,
  },
  {
    id: 6,
    name: 'Prime Hospital Peshawar',
    address: 'University Road, Peshawar',
    area: 'University Road',
    contactNumber: '+92-91-5702233',
    oracleCustomerCode: 'CUST-121528',
    paymentTerms: 'credit',
    confirmMethod: 'otp',
    defaultRouteId: 1,
    creditLimit: 2500000,
    outstanding: 831000,
  },
  {
    id: 7,
    name: 'New Malik Hardware Store Shoba Bazar',
    address: 'Shoba Bazar, Peshawar City',
    area: 'Shoba Bazar',
    contactNumber: '+92-345-9102277',
    oracleCustomerCode: 'CUST-121293',
    paymentTerms: 'cash',
    confirmMethod: 'signature',
    defaultRouteId: 4,
    creditLimit: 0,
    outstanding: 0,
  },
  {
    id: 8,
    name: 'Irfan General Hospital',
    address: 'Sardar Garhi, Peshawar',
    area: 'Sardar Garhi',
    contactNumber: '+92-91-5843300',
    oracleCustomerCode: 'CUST-120569',
    paymentTerms: 'credit',
    confirmMethod: 'otp',
    defaultRouteId: 1,
    creditLimit: 2000000,
    outstanding: 697000,
  },
  {
    id: 9,
    name: 'Bangash Peshawar',
    address: 'Ring Road, Peshawar',
    area: 'Ring Road',
    contactNumber: '+92-301-8845512',
    oracleCustomerCode: 'CUST-119686',
    paymentTerms: 'credit',
    confirmMethod: 'signature',
    defaultRouteId: 2,
    creditLimit: 2000000,
    outstanding: 614000,
  },
  {
    id: 10,
    name: 'Al Khidmat Medical Complex',
    address: 'Warsak Road, Peshawar',
    area: 'Warsak Road',
    contactNumber: '+92-91-2313355',
    oracleCustomerCode: 'CUST-119382',
    paymentTerms: 'credit',
    confirmMethod: 'otp',
    defaultRouteId: 3,
    creditLimit: 2000000,
    outstanding: 593000,
  },
  {
    id: 11,
    name: 'Health Net Hospital',
    address: 'Charsadda Road, Peshawar',
    area: 'Charsadda Road',
    contactNumber: '+92-91-2620077',
    oracleCustomerCode: 'CUST-137841',
    paymentTerms: 'credit',
    confirmMethod: 'otp',
    defaultRouteId: 2,
    creditLimit: 1800000,
    outstanding: 590000,
  },
  {
    id: 12,
    name: 'Haji Gul Tayaz Khan Govt. Contractor and Gas Supplier',
    address: 'GT Road, Peshawar',
    area: 'GT Road',
    contactNumber: '+92-333-9445566',
    oracleCustomerCode: 'CUST-143806',
    paymentTerms: 'cash',
    confirmMethod: 'signature',
    defaultRouteId: 4,
    creditLimit: 0,
    outstanding: 0,
  },
  {
    id: 13,
    name: 'Director Breed Improvement Livestock Warsak Road Peshawar',
    address: 'Breed Improvement Centre, Warsak Road, Peshawar',
    area: 'Warsak Road',
    contactNumber: '+92-91-9216644',
    oracleCustomerCode: 'CUST-120807',
    paymentTerms: 'credit',
    confirmMethod: 'signature',
    defaultRouteId: 3,
    creditLimit: 1500000,
    outstanding: 297000,
  },
  {
    id: 14,
    name: 'Shahzad LN2',
    address: 'Pajjagi Road, Peshawar',
    area: 'Pajjagi Road',
    contactNumber: '+92-346-7712390',
    oracleCustomerCode: 'CUST-137699',
    paymentTerms: 'cash',
    confirmMethod: 'otp',
    defaultRouteId: 4,
    creditLimit: 0,
    outstanding: 0,
  },
  {
    id: 15,
    name: 'Al-Heavan Sires',
    address: 'Nasir Bagh Road, Peshawar',
    area: 'Nasir Bagh',
    contactNumber: '+92-311-4459087',
    oracleCustomerCode: 'CUST-142384',
    paymentTerms: 'credit',
    confirmMethod: 'signature',
    defaultRouteId: 3,
    creditLimit: 1000000,
    outstanding: 186000,
  },
  {
    id: 16,
    name: 'Zahid Ullah (Cash Sale)',
    address: 'Faqirabad, Peshawar',
    area: 'Faqirabad',
    contactNumber: '+92-314-7788201',
    oracleCustomerCode: 'CUST-122319',
    paymentTerms: 'cash',
    confirmMethod: 'otp',
    defaultRouteId: 4,
    creditLimit: 0,
    outstanding: 0,
  },
];

/**
 * Monthly transaction counts from the report, for the admin dashboard chart.
 * `orders` = distinct sale/delivery documents in that month at Peshawar.
 * `cylinders` = estimated cylinder count (gas QTY / cylinder size, plus
 * unit-of-measure 'Units' lines). `valuePkr` = sum of Inc.Adv Tax value.
 */
export const monthlyVolume: { month: string; orders: number; cylinders: number; valuePkr: number }[] = [
  { month: '2025-07', orders: 527, cylinders: 1896, valuePkr: 19622704 },
  { month: '2025-08', orders: 555, cylinders: 2013, valuePkr: 21017419 },
  { month: '2025-09', orders: 612, cylinders: 2005, valuePkr: 19159085 },
  { month: '2025-10', orders: 650, cylinders: 1884, valuePkr: 25542812 },
  { month: '2025-11', orders: 538, cylinders: 1459, valuePkr: 20940764 },
  { month: '2025-12', orders: 648, cylinders: 3079, valuePkr: 24462417 },
  { month: '2026-01', orders: 641, cylinders: 2358, valuePkr: 24637589 },
  { month: '2026-02', orders: 515, cylinders: 1666, valuePkr: 19345042 },
  { month: '2026-03', orders: 518, cylinders: 1974, valuePkr: 21587562 },
  { month: '2026-04', orders: 560, cylinders: 1977, valuePkr: 21057631 },
  { month: '2026-05', orders: 546, cylinders: 1703, valuePkr: 24000756 },
  { month: '2026-06', orders: 578, cylinders: 1949, valuePkr: 22002355 },
];

/** Headline facts for the demo's "real data" callout. */
export const dataProvenance = {
  sourceFile: 'Peshawar Sale & Purchase Report June 25 to July 26.xlsx',
  warehouse: 'Peshawar',
  periodFrom: '2025-07-01',
  periodTo: '2026-06-29',
  totalTransactions: 6888,
  totalCylinders: 23963,
  totalValuePkr: 263376135,
  peakMonthTransactions: 650,
};
